df <- read.table("household_power_consumption.txt",header = TRUE, na.strings = "?", sep = ";")
df$Time <- strptime(paste(df$Date," ",df$Time), format = "%d/%m/%Y %H:%M:%S")
df$Date <- as.Date(df$Date, format = "%d/%m/%Y")
feb <- df[df$Date == "2007-02-01" | df$Date == "2007-02-02",]
par(mfrow = c(2, 2))
with (feb, plot(Time, Global_active_power, type = "l", xlab = "", ylab = "Global Active Power"))
with (feb, plot(Time, Voltage, type = "l", xlab = "datetime", ylab = "Volatage"))
with (feb, {
        plot(Time, Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
        lines(Time, Sub_metering_2, type = "l", col = "red")
        lines(Time, Sub_metering_3, type = "l", col = "blue")
})
legend("topright", lwd = "1", bty = "n", col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
with (feb, plot(Time, Global_reactive_power, type = "l", xlab = "datetime"))
dev.copy(png, file = "plot4.png")
dev.off()